language: csharp
solution: IdSharp.sln
install:
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release IdSharp.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Tests/IdSharp.Common.Tests/bin/Release/IdSharp.Common.Tests.dll
